### PR TITLE
use File#write to avoid adding LF characters

### LINKED ISSUE #29: Trailing LF character is added when content files are zipped
I noticed willow_sword adds a trailing LF character to content files when it creates a zip file. The following is an example to create a zip file for ``public`` directory in a Rails project.

```
$ rails c
> file = WillowSword::ZipPackage.new('public', 'data/test.zip')
> file.create_zip
```

```
$ unzip test.zip -d tmp
$ diff -u tmp/apple-touch-icon.png hyrax/public/apple-touch-icon.png
Binary files tmp/apple-touch-icon.png and hyrax/public/apple-touch-icon.png differ
$ cmp tmp/apple-touch-icon.png hyrax/public/apple-touch-icon.png
cmp: EOF on hyrax/public/apple-touch-icon.png after byte 5401, in line 26
```

### PR DESCRIPTION
**Pull request by nabeta**
This PR will fix https://github.com/CottageLabs/willow_sword/issues/29 .

### CODE REVIEW

**Review by Steven-Eardley — APPROVED** [review]

**Comment by Steven-Eardley** [comment]
@nabeta zip test fails on CI and locally, I've reverted master after merging this in (it remains in develop)

```ruby
/home/rof/cache/bundler/ruby/2.6.0/gems/shoulda-matchers-3.1.2/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:273: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
......................F

Failures:

1) WillowSword::ZipPackage unzip_file should zip the source containing files and dir
Failure/Error: expect(test_zip(@zip_src, dst)).to be_truthy

  expected: truthy value
       got: false
# ./spec/lib/willow_sword/zip_package_spec.rb:28:in `block (3 levels) in <top (required)>'

Finished in 0.1758 seconds (files took 1.72 seconds to load)
23 examples, 1 failure

Failed examples:

rspec ./spec/lib/willow_sword/zip_package_spec.rb:23 # WillowSword::ZipPackage unzip_file should zip the source containing files and dir
```

**Comment by Steven-Eardley** [comment]
although this test was failing before the new changes too.

**Comment by nabeta** [comment]
@Steven-Eardley The test passes on my Linux desktop.

```
$ bundle exec rake
/home/kosuke/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/shoulda-matchers-3.1.2/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:273: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
/home/kosuke/.rbenv/versions/2.6.6/bin/ruby -I/home/kosuke/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-core-3.7.1/lib:/home/kosuke/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-support-3.7.1/lib /home/kosuke/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rspec-core-3.7.1/exe/rspec spec/lib/willow_sword/bag_package_spec.rb spec/lib/willow_sword/dc_crosswalk_spec.rb spec/lib/willow_sword/error_spec.rb spec/lib/willow_sword/zip_package_spec.rb
/home/kosuke/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/shoulda-matchers-3.1.2/lib/shoulda/matchers/active_model/validate_inclusion_of_matcher.rb:273: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
.......................

Finished in 0.14149 seconds (files took 1.53 seconds to load)
23 examples, 0 failures
```

I've added a debug output. Could you try my latest commit?
https://github.com/nabeta/willow_sword/commit/38b548f5425e1cd4d2cc1b59a731d81e3ceb0441

**Comment by Steven-Eardley** [comment]
Thanks, it was just the ordering of md5; adding a `.sort!` to the comparison was the solution to make the tests pass.

**Pull request merged**
